/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  AttributeBasedVMSizeRecommenderInput,
  AttributeBasedVMSizeRecommenderPostOptionalParams,
  AttributeBasedVMSizeRecommenderPostResponse,
} from "../models/index.js";

/** Interface representing a AttributeBasedVMSizeRecommender. */
export interface AttributeBasedVMSizeRecommender {
  /**
   * Generates attribute based VM Size Recommendations.
   * @param location The name of the Azure region.
   * @param attributeBasedVMSizeRecommenderInput AttributeBasedVMSizeRecommender object supplied in the
   *                                             body of the Post attribute based VMSize recommender operation.
   * @param options The options parameters.
   */
  post(
    location: string,
    attributeBasedVMSizeRecommenderInput: AttributeBasedVMSizeRecommenderInput,
    options?: AttributeBasedVMSizeRecommenderPostOptionalParams,
  ): Promise<AttributeBasedVMSizeRecommenderPostResponse>;
}
