/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  DiagnosticOperationsReadOptionalParams,
  DiagnosticOperationsReadResponse,
} from "../models/index.js";

/** Interface representing a DiagnosticOperations. */
export interface DiagnosticOperations {
  /**
   * Gets status of a Diagnostic operation issued for Disk Inspection.
   * @param location The name of the Azure region.
   * @param operationId The ID of an ongoing async operation.
   * @param options The options parameters.
   */
  read(
    location: string,
    operationId: string,
    options?: DiagnosticOperationsReadOptionalParams,
  ): Promise<DiagnosticOperationsReadResponse>;
}
