/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { PagedAsyncIterableIterator } from "@azure/core-paging";
import {
  ComputeDiagnosticBase,
  DiagnosticsListOptionalParams,
} from "../models/index.js";

/// <reference lib="esnext.asynciterable" />
/** Interface representing a Diagnostics. */
export interface Diagnostics {
  /**
   * Lists all available Compute diagnostics for a subscription in a location.
   * @param location The name of the Azure region.
   * @param options The options parameters.
   */
  list(
    location: string,
    options?: DiagnosticsListOptionalParams,
  ): PagedAsyncIterableIterator<ComputeDiagnosticBase>;
}
