/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  StorageConfigurationInput,
  DiskInspectionStorageConfigurationRegisterOptionalParams,
  DiskInspectionStorageConfigurationValidateOptionalParams,
  DiskInspectionStorageConfigurationValidateResponse,
} from "../models/index.js";

/** Interface representing a DiskInspectionStorageConfiguration. */
export interface DiskInspectionStorageConfiguration {
  /**
   * Register a storageAccount for a subscription used for DiskInspection
   * @param location The name of the Azure region.
   * @param storageConfigurationInput Storage Configuration object supplied in the body of the Post to
   *                                  cache storageAccount for a given subscription.
   * @param options The options parameters.
   */
  register(
    location: string,
    storageConfigurationInput: StorageConfigurationInput,
    options?: DiskInspectionStorageConfigurationRegisterOptionalParams,
  ): Promise<void>;
  /**
   * Validate if a storageAccount configuration exists for a subscription used for DiskInspection.
   * @param location The name of the Azure region.
   * @param options The options parameters.
   */
  validate(
    location: string,
    options?: DiskInspectionStorageConfigurationValidateOptionalParams,
  ): Promise<DiskInspectionStorageConfigurationValidateResponse>;
}
