/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  SpotPlacementScoresGetOptionalParams,
  SpotPlacementScoresGetResponse,
  SpotPlacementScoresInput,
  SpotPlacementScoresPostOptionalParams,
  SpotPlacementScoresPostResponse,
} from "../models/index.js";

/** Interface representing a SpotPlacementScores. */
export interface SpotPlacementScores {
  /**
   * Gets Spot Placement Scores metadata.
   * @param location The name of the Azure region.
   * @param options The options parameters.
   */
  get(
    location: string,
    options?: SpotPlacementScoresGetOptionalParams,
  ): Promise<SpotPlacementScoresGetResponse>;
  /**
   * Generates placement scores for Spot VM skus.
   * @param location The name of the Azure region.
   * @param spotPlacementScoresInput SpotPlacementScores object supplied in the body of the Post spot
   *                                 placement scores operation.
   * @param options The options parameters.
   */
  post(
    location: string,
    spotPlacementScoresInput: SpotPlacementScoresInput,
    options?: SpotPlacementScoresPostOptionalParams,
  ): Promise<SpotPlacementScoresPostResponse>;
}
