/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import {
  SpotPlacementRecommenderGetOptionalParams,
  SpotPlacementRecommenderGetResponse,
  SpotPlacementRecommenderInput,
  SpotPlacementRecommenderPostOptionalParams,
  SpotPlacementRecommenderPostResponse,
} from "../models/index.js";

/** Interface representing a SpotPlacementRecommender. */
export interface SpotPlacementRecommender {
  /**
   * [SOON TO BE DEPRECATED] Gets Spot Placement Recommender diagnostic metadata.
   * @param location The name of the Azure region.
   * @param options The options parameters.
   */
  get(
    location: string,
    options?: SpotPlacementRecommenderGetOptionalParams,
  ): Promise<SpotPlacementRecommenderGetResponse>;
  /**
   * [SOON TO BE DEPRECATED] Generates placement scores for Spot VM skus.
   * @param location The name of the Azure region.
   * @param spotPlacementRecommenderInput SpotPlacementRecommender object supplied in the body of the
   *                                      Post spot placement recommender operation.
   * @param options The options parameters.
   */
  post(
    location: string,
    spotPlacementRecommenderInput: SpotPlacementRecommenderInput,
    options?: SpotPlacementRecommenderPostOptionalParams,
  ): Promise<SpotPlacementRecommenderPostResponse>;
}
