/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/dataSourcesMappers";
import * as Parameters from "../models/parameters";
import { OperationalInsightsManagementClientContext } from "../operationalInsightsManagementClientContext";

/** Class representing a DataSources. */
export class DataSources {
  private readonly client: OperationalInsightsManagementClientContext;

  /**
   * Create a DataSources.
   * @param {OperationalInsightsManagementClientContext} client Reference to the service client.
   */
  constructor(client: OperationalInsightsManagementClientContext) {
    this.client = client;
  }

  /**
   * Create or update a data source.
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName The name of the datasource resource.
   * @param parameters The parameters required to create or update a datasource.
   * @param [options] The optional parameters
   * @returns Promise<Models.DataSourcesCreateOrUpdateResponse>
   */
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, parameters: Models.DataSource, options?: msRest.RequestOptionsBase): Promise<Models.DataSourcesCreateOrUpdateResponse>;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName The name of the datasource resource.
   * @param parameters The parameters required to create or update a datasource.
   * @param callback The callback
   */
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, parameters: Models.DataSource, callback: msRest.ServiceCallback<Models.DataSource>): void;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName The name of the datasource resource.
   * @param parameters The parameters required to create or update a datasource.
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, parameters: Models.DataSource, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DataSource>): void;
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, parameters: Models.DataSource, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DataSource>, callback?: msRest.ServiceCallback<Models.DataSource>): Promise<Models.DataSourcesCreateOrUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        subscriptionId,
        resourceGroupName,
        workspaceName,
        dataSourceName,
        parameters,
        options
      },
      createOrUpdateOperationSpec,
      callback) as Promise<Models.DataSourcesCreateOrUpdateResponse>;
  }

  /**
   * Deletes a data source instance.
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName Name of the datasource.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName Name of the datasource.
   * @param callback The callback
   */
  deleteMethod(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName Name of the datasource.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        subscriptionId,
        resourceGroupName,
        workspaceName,
        dataSourceName,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }

  /**
   * Gets a datasource instance.
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName Name of the datasource
   * @param [options] The optional parameters
   * @returns Promise<Models.DataSourcesGetResponse>
   */
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, options?: msRest.RequestOptionsBase): Promise<Models.DataSourcesGetResponse>;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName Name of the datasource
   * @param callback The callback
   */
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, callback: msRest.ServiceCallback<Models.DataSource>): void;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param dataSourceName Name of the datasource
   * @param options The optional parameters
   * @param callback The callback
   */
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DataSource>): void;
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, dataSourceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DataSource>, callback?: msRest.ServiceCallback<Models.DataSource>): Promise<Models.DataSourcesGetResponse> {
    return this.client.sendOperationRequest(
      {
        subscriptionId,
        resourceGroupName,
        workspaceName,
        dataSourceName,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.DataSourcesGetResponse>;
  }

  /**
   * Gets the first page of data source instances in a workspace with the link to the next page.
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param filter The filter to apply on the operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.DataSourcesListByWorkspaceResponse>
   */
  listByWorkspace(subscriptionId: string, resourceGroupName: string, workspaceName: string, filter: string, options?: Models.DataSourcesListByWorkspaceOptionalParams): Promise<Models.DataSourcesListByWorkspaceResponse>;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param filter The filter to apply on the operation.
   * @param callback The callback
   */
  listByWorkspace(subscriptionId: string, resourceGroupName: string, workspaceName: string, filter: string, callback: msRest.ServiceCallback<Models.DataSourceListResult>): void;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param filter The filter to apply on the operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listByWorkspace(subscriptionId: string, resourceGroupName: string, workspaceName: string, filter: string, options: Models.DataSourcesListByWorkspaceOptionalParams, callback: msRest.ServiceCallback<Models.DataSourceListResult>): void;
  listByWorkspace(subscriptionId: string, resourceGroupName: string, workspaceName: string, filter: string, options?: Models.DataSourcesListByWorkspaceOptionalParams | msRest.ServiceCallback<Models.DataSourceListResult>, callback?: msRest.ServiceCallback<Models.DataSourceListResult>): Promise<Models.DataSourcesListByWorkspaceResponse> {
    return this.client.sendOperationRequest(
      {
        subscriptionId,
        resourceGroupName,
        workspaceName,
        filter,
        options
      },
      listByWorkspaceOperationSpec,
      callback) as Promise<Models.DataSourcesListByWorkspaceResponse>;
  }

  /**
   * Gets the first page of data source instances in a workspace with the link to the next page.
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.DataSourcesListByWorkspaceNextResponse>
   */
  listByWorkspaceNext(nextPageLink: string, options?: msRest.RequestOptionsBase): Promise<Models.DataSourcesListByWorkspaceNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listByWorkspaceNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.DataSourceListResult>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listByWorkspaceNext(nextPageLink: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DataSourceListResult>): void;
  listByWorkspaceNext(nextPageLink: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DataSourceListResult>, callback?: msRest.ServiceCallback<Models.DataSourceListResult>): Promise<Models.DataSourcesListByWorkspaceNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listByWorkspaceNextOperationSpec,
      callback) as Promise<Models.DataSourcesListByWorkspaceNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const createOrUpdateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/dataSources/{dataSourceName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName,
    Parameters.dataSourceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "parameters",
    mapper: {
      ...Mappers.DataSource,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.DataSource
    },
    201: {
      bodyMapper: Mappers.DataSource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/dataSources/{dataSourceName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName,
    Parameters.dataSourceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {},
    204: {},
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/dataSources/{dataSourceName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName,
    Parameters.dataSourceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DataSource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listByWorkspaceOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/dataSources",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.filter,
    Parameters.skiptoken
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DataSourceListResult
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listByWorkspaceNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DataSourceListResult
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
