/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/tablesMappers";
import * as Parameters from "../models/parameters";
import { OperationalInsightsManagementClientContext } from "../operationalInsightsManagementClientContext";

/** Class representing a Tables. */
export class Tables {
  private readonly client: OperationalInsightsManagementClientContext;

  /**
   * Create a Tables.
   * @param {OperationalInsightsManagementClientContext} client Reference to the service client.
   */
  constructor(client: OperationalInsightsManagementClientContext) {
    this.client = client;
  }

  /**
   * Sets a Log Analytics workspace table properties.
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param tableName The name of the table.
   * @param parameters The parameters required to set table properties.
   * @param [options] The optional parameters
   * @returns Promise<Models.TablesCreateOrUpdateResponse>
   */
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, parameters: Models.Table, options?: msRest.RequestOptionsBase): Promise<Models.TablesCreateOrUpdateResponse>;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param tableName The name of the table.
   * @param parameters The parameters required to set table properties.
   * @param callback The callback
   */
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, parameters: Models.Table, callback: msRest.ServiceCallback<Models.Table>): void;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param tableName The name of the table.
   * @param parameters The parameters required to set table properties.
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, parameters: Models.Table, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Table>): void;
  createOrUpdate(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, parameters: Models.Table, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Table>, callback?: msRest.ServiceCallback<Models.Table>): Promise<Models.TablesCreateOrUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        subscriptionId,
        resourceGroupName,
        workspaceName,
        tableName,
        parameters,
        options
      },
      createOrUpdateOperationSpec,
      callback) as Promise<Models.TablesCreateOrUpdateResponse>;
  }

  /**
   * Gets a Log Analytics workspace table.
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param tableName The name of the table.
   * @param [options] The optional parameters
   * @returns Promise<Models.TablesGetResponse>
   */
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, options?: msRest.RequestOptionsBase): Promise<Models.TablesGetResponse>;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param tableName The name of the table.
   * @param callback The callback
   */
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, callback: msRest.ServiceCallback<Models.Table>): void;
  /**
   * @param subscriptionId Gets subscription credentials which uniquely identify Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param resourceGroupName The name of the resource group to get. The name is case insensitive.
   * @param workspaceName The name of the workspace.
   * @param tableName The name of the table.
   * @param options The optional parameters
   * @param callback The callback
   */
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Table>): void;
  get(subscriptionId: string, resourceGroupName: string, workspaceName: string, tableName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Table>, callback?: msRest.ServiceCallback<Models.Table>): Promise<Models.TablesGetResponse> {
    return this.client.sendOperationRequest(
      {
        subscriptionId,
        resourceGroupName,
        workspaceName,
        tableName,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.TablesGetResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const createOrUpdateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/tables/{tableName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName,
    Parameters.tableName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "parameters",
    mapper: {
      ...Mappers.Table,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.Table
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/tables/{tableName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName,
    Parameters.tableName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.Table
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
