/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/partnerTransfersMappers";
import * as Parameters from "../models/parameters";
import { BillingManagementClientContext } from "../billingManagementClientContext";

/** Class representing a PartnerTransfers. */
export class PartnerTransfers {
  private readonly client: BillingManagementClientContext;

  /**
   * Create a PartnerTransfers.
   * @param {BillingManagementClientContext} client Reference to the service client.
   */
  constructor(client: BillingManagementClientContext) {
    this.client = client;
  }

  /**
   * Initiates the request to transfer the legacy subscriptions or RIs.
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param parameters Parameters supplied to initiate the transfer.
   * @param [options] The optional parameters
   * @returns Promise<Models.PartnerTransfersInitiateResponse>
   */
  initiate(billingAccountName: string, billingProfileName: string, customerName: string, parameters: Models.InitiateTransferRequest, options?: msRest.RequestOptionsBase): Promise<Models.PartnerTransfersInitiateResponse>;
  /**
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param parameters Parameters supplied to initiate the transfer.
   * @param callback The callback
   */
  initiate(billingAccountName: string, billingProfileName: string, customerName: string, parameters: Models.InitiateTransferRequest, callback: msRest.ServiceCallback<Models.TransferDetails>): void;
  /**
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param parameters Parameters supplied to initiate the transfer.
   * @param options The optional parameters
   * @param callback The callback
   */
  initiate(billingAccountName: string, billingProfileName: string, customerName: string, parameters: Models.InitiateTransferRequest, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.TransferDetails>): void;
  initiate(billingAccountName: string, billingProfileName: string, customerName: string, parameters: Models.InitiateTransferRequest, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.TransferDetails>, callback?: msRest.ServiceCallback<Models.TransferDetails>): Promise<Models.PartnerTransfersInitiateResponse> {
    return this.client.sendOperationRequest(
      {
        billingAccountName,
        billingProfileName,
        customerName,
        parameters,
        options
      },
      initiateOperationSpec,
      callback) as Promise<Models.PartnerTransfersInitiateResponse>;
  }

  /**
   * Gets the transfer details for given transfer Id.
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param transferName Transfer Name.
   * @param [options] The optional parameters
   * @returns Promise<Models.PartnerTransfersGetResponse>
   */
  get(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, options?: msRest.RequestOptionsBase): Promise<Models.PartnerTransfersGetResponse>;
  /**
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param transferName Transfer Name.
   * @param callback The callback
   */
  get(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, callback: msRest.ServiceCallback<Models.TransferDetails>): void;
  /**
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param transferName Transfer Name.
   * @param options The optional parameters
   * @param callback The callback
   */
  get(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.TransferDetails>): void;
  get(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.TransferDetails>, callback?: msRest.ServiceCallback<Models.TransferDetails>): Promise<Models.PartnerTransfersGetResponse> {
    return this.client.sendOperationRequest(
      {
        billingAccountName,
        billingProfileName,
        customerName,
        transferName,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.PartnerTransfersGetResponse>;
  }

  /**
   * Cancels the transfer for given transfer Id.
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param transferName Transfer Name.
   * @param [options] The optional parameters
   * @returns Promise<Models.PartnerTransfersCancelResponse>
   */
  cancel(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, options?: msRest.RequestOptionsBase): Promise<Models.PartnerTransfersCancelResponse>;
  /**
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param transferName Transfer Name.
   * @param callback The callback
   */
  cancel(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, callback: msRest.ServiceCallback<Models.TransferDetails>): void;
  /**
   * @param billingAccountName billing Account Id.
   * @param billingProfileName Billing Profile Id.
   * @param customerName Customer name.
   * @param transferName Transfer Name.
   * @param options The optional parameters
   * @param callback The callback
   */
  cancel(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.TransferDetails>): void;
  cancel(billingAccountName: string, billingProfileName: string, customerName: string, transferName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.TransferDetails>, callback?: msRest.ServiceCallback<Models.TransferDetails>): Promise<Models.PartnerTransfersCancelResponse> {
    return this.client.sendOperationRequest(
      {
        billingAccountName,
        billingProfileName,
        customerName,
        transferName,
        options
      },
      cancelOperationSpec,
      callback) as Promise<Models.PartnerTransfersCancelResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const initiateOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/customers/{customerName}/initiateTransfer",
  urlParameters: [
    Parameters.billingAccountName,
    Parameters.billingProfileName,
    Parameters.customerName
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "parameters",
    mapper: {
      ...Mappers.InitiateTransferRequest,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.TransferDetails
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};

const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/customers/{customerName}/transfers/{transferName}",
  urlParameters: [
    Parameters.billingAccountName,
    Parameters.billingProfileName,
    Parameters.customerName,
    Parameters.transferName
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.TransferDetails
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};

const cancelOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "providers/Microsoft.Billing/billingAccounts/{billingAccountName}/billingProfiles/{billingProfileName}/customers/{customerName}/transfers/{transferName}",
  urlParameters: [
    Parameters.billingAccountName,
    Parameters.billingProfileName,
    Parameters.customerName,
    Parameters.transferName
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.TransferDetails
    },
    default: {
      bodyMapper: Mappers.ErrorResponse
    }
  },
  serializer
};
