/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/backupCrrJobDetailsMappers";
import * as Parameters from "../models/parameters";
import { RecoveryServicesBackupClientContext } from "../recoveryServicesBackupClientContext";

/** Class representing a BackupCrrJobDetails. */
export class BackupCrrJobDetails {
  private readonly client: RecoveryServicesBackupClientContext;

  /**
   * Create a BackupCrrJobDetails.
   * @param {RecoveryServicesBackupClientContext} client Reference to the service client.
   */
  constructor(client: RecoveryServicesBackupClientContext) {
    this.client = client;
  }

  /**
   * @summary Get CRR job details from target region.
   * @param azureRegion Azure region to hit Api
   * @param [options] The optional parameters
   * @returns Promise<Models.BackupCrrJobDetailsGetResponse>
   */
  get(azureRegion: string, options?: msRest.RequestOptionsBase): Promise<Models.BackupCrrJobDetailsGetResponse>;
  /**
   * @param azureRegion Azure region to hit Api
   * @param callback The callback
   */
  get(azureRegion: string, callback: msRest.ServiceCallback<Models.JobResource>): void;
  /**
   * @param azureRegion Azure region to hit Api
   * @param options The optional parameters
   * @param callback The callback
   */
  get(azureRegion: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JobResource>): void;
  get(azureRegion: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JobResource>, callback?: msRest.ServiceCallback<Models.JobResource>): Promise<Models.BackupCrrJobDetailsGetResponse> {
    return this.client.sendOperationRequest(
      {
        azureRegion,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.BackupCrrJobDetailsGetResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "Subscriptions/{subscriptionId}/providers/Microsoft.RecoveryServices/locations/{azureRegion}/backupCrrJob",
  urlParameters: [
    Parameters.azureRegion,
    Parameters.subscriptionId
  ],
  queryParameters: [
    Parameters.apiVersion1
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.JobResource
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
