/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/crossRegionRestoreMappers";
import * as Parameters from "../models/parameters";
import { RecoveryServicesBackupClientContext } from "../recoveryServicesBackupClientContext";

/** Class representing a CrossRegionRestore. */
export class CrossRegionRestore {
  private readonly client: RecoveryServicesBackupClientContext;

  /**
   * Create a CrossRegionRestore.
   * @param {RecoveryServicesBackupClientContext} client Reference to the service client.
   */
  constructor(client: RecoveryServicesBackupClientContext) {
    this.client = client;
  }

  /**
   * @summary Restores the specified backed up data in a different region as compared to where the
   * data is backed up.
   * @param azureRegion Azure region to hit Api
   * @param parameters resource cross region restore request
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  trigger(azureRegion: string, parameters: Models.CrossRegionRestoreRequestResource, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param azureRegion Azure region to hit Api
   * @param parameters resource cross region restore request
   * @param callback The callback
   */
  trigger(azureRegion: string, parameters: Models.CrossRegionRestoreRequestResource, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param azureRegion Azure region to hit Api
   * @param parameters resource cross region restore request
   * @param options The optional parameters
   * @param callback The callback
   */
  trigger(azureRegion: string, parameters: Models.CrossRegionRestoreRequestResource, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  trigger(azureRegion: string, parameters: Models.CrossRegionRestoreRequestResource, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        azureRegion,
        parameters,
        options
      },
      triggerOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const triggerOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "Subscriptions/{subscriptionId}/providers/Microsoft.RecoveryServices/locations/{azureRegion}/backupCrossRegionRestore",
  urlParameters: [
    Parameters.azureRegion,
    Parameters.subscriptionId
  ],
  queryParameters: [
    Parameters.apiVersion1
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "parameters",
    mapper: {
      ...Mappers.CrossRegionRestoreRequestResource,
      required: true
    }
  },
  responses: {
    202: {},
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
