/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { CloudErrorMapper, BaseResourceMapper } from "@azure/ms-rest-azure-js";
import * as msRest from "@azure/ms-rest-js";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const ErrorResponse: msRest.CompositeMapper = {
  serializedName: "ErrorResponse",
  type: {
    name: "Composite",
    className: "ErrorResponse",
    modelProperties: {
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const OperationDisplay: msRest.CompositeMapper = {
  serializedName: "Operation_display",
  type: {
    name: "Composite",
    className: "OperationDisplay",
    modelProperties: {
      provider: {
        serializedName: "provider",
        type: {
          name: "String"
        }
      },
      resource: {
        serializedName: "resource",
        type: {
          name: "String"
        }
      },
      operation: {
        serializedName: "operation",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const Operation: msRest.CompositeMapper = {
  serializedName: "Operation",
  type: {
    name: "Composite",
    className: "Operation",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      display: {
        serializedName: "display",
        type: {
          name: "Composite",
          className: "OperationDisplay"
        }
      }
    }
  }
};

export const WorkbookTemplateResource: msRest.CompositeMapper = {
  serializedName: "WorkbookTemplateResource",
  type: {
    name: "Composite",
    className: "WorkbookTemplateResource",
    modelProperties: {
      resourceId: {
        readOnly: true,
        serializedName: "resourceId",
        type: {
          name: "String"
        }
      },
      name: {
        readOnly: true,
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      type: {
        readOnly: true,
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      location: {
        required: true,
        serializedName: "location",
        type: {
          name: "String"
        }
      },
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      }
    }
  }
};

export const WorkbookTemplateGallery: msRest.CompositeMapper = {
  serializedName: "WorkbookTemplateGallery",
  type: {
    name: "Composite",
    className: "WorkbookTemplateGallery",
    modelProperties: {
      name: {
        serializedName: "name",
        type: {
          name: "String"
        }
      },
      category: {
        serializedName: "category",
        type: {
          name: "String"
        }
      },
      type: {
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      order: {
        serializedName: "order",
        type: {
          name: "Number"
        }
      },
      resourceType: {
        serializedName: "resourceType",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WorkbookTemplateLocalizedGallery: msRest.CompositeMapper = {
  serializedName: "WorkbookTemplateLocalizedGallery",
  type: {
    name: "Composite",
    className: "WorkbookTemplateLocalizedGallery",
    modelProperties: {
      templateData: {
        serializedName: "templateData",
        type: {
          name: "Object"
        }
      },
      galleries: {
        serializedName: "galleries",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WorkbookTemplateGallery"
            }
          }
        }
      }
    }
  }
};

export const WorkbookTemplate: msRest.CompositeMapper = {
  serializedName: "WorkbookTemplate",
  type: {
    name: "Composite",
    className: "WorkbookTemplate",
    modelProperties: {
      ...WorkbookTemplateResource.type.modelProperties,
      id: {
        required: true,
        serializedName: "properties.id",
        type: {
          name: "String"
        }
      },
      priority: {
        serializedName: "properties.priority",
        type: {
          name: "Number"
        }
      },
      author: {
        serializedName: "properties.author",
        type: {
          name: "String"
        }
      },
      templateData: {
        required: true,
        serializedName: "properties.templateData",
        type: {
          name: "Object"
        }
      },
      galleries: {
        required: true,
        serializedName: "properties.galleries",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WorkbookTemplateGallery"
            }
          }
        }
      },
      localized: {
        serializedName: "properties.localized",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Composite",
                  className: "WorkbookTemplateLocalizedGallery"
                }
              }
            }
          }
        }
      }
    }
  }
};

export const WorkbookTemplateUpdateParameters: msRest.CompositeMapper = {
  serializedName: "WorkbookTemplateUpdateParameters",
  type: {
    name: "Composite",
    className: "WorkbookTemplateUpdateParameters",
    modelProperties: {
      tags: {
        serializedName: "tags",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "String"
            }
          }
        }
      },
      id: {
        required: true,
        serializedName: "properties.id",
        type: {
          name: "String"
        }
      },
      priority: {
        serializedName: "properties.priority",
        type: {
          name: "Number"
        }
      },
      author: {
        serializedName: "properties.author",
        type: {
          name: "String"
        }
      },
      templateData: {
        required: true,
        serializedName: "properties.templateData",
        type: {
          name: "Object"
        }
      },
      galleries: {
        required: true,
        serializedName: "properties.galleries",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WorkbookTemplateGallery"
            }
          }
        }
      },
      localized: {
        serializedName: "properties.localized",
        type: {
          name: "Dictionary",
          value: {
            type: {
              name: "Sequence",
              element: {
                type: {
                  name: "Composite",
                  className: "WorkbookTemplateLocalizedGallery"
                }
              }
            }
          }
        }
      }
    }
  }
};

export const ErrorFieldContract: msRest.CompositeMapper = {
  serializedName: "ErrorFieldContract",
  type: {
    name: "Composite",
    className: "ErrorFieldContract",
    modelProperties: {
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      },
      target: {
        serializedName: "target",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WorkbookError: msRest.CompositeMapper = {
  serializedName: "WorkbookError",
  type: {
    name: "Composite",
    className: "WorkbookError",
    modelProperties: {
      code: {
        serializedName: "code",
        type: {
          name: "String"
        }
      },
      message: {
        serializedName: "message",
        type: {
          name: "String"
        }
      },
      details: {
        serializedName: "details",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "ErrorFieldContract"
            }
          }
        }
      }
    }
  }
};

export const OperationListResult: msRest.CompositeMapper = {
  serializedName: "OperationListResult",
  type: {
    name: "Composite",
    className: "OperationListResult",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Operation"
            }
          }
        }
      },
      nextLink: {
        serializedName: "nextLink",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const WorkbookTemplatesListResult: msRest.CompositeMapper = {
  serializedName: "WorkbookTemplatesListResult",
  type: {
    name: "Composite",
    className: "WorkbookTemplatesListResult",
    modelProperties: {
      value: {
        serializedName: "",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "WorkbookTemplate"
            }
          }
        }
      }
    }
  }
};
